@startwbs 副菜を作るWBS
title マカロニサラダを作る
+ マカロニサラダを作る
** 下準備する
+++ マカロニを茹でる
*** 玉ねぎ、にんじんを細かく切り電子レンジで加熱する
*** きゅうりを輪切りにする
*** ハムを切る
** 味付けする
+++ 全ての材料を合わせ、マヨネーズで合える
*** 塩コショウで味を整える
** 盛り付けをする
+++ お皿にレタスを乗せる
*** マカロニサラダをさらに乗せる
@endwbs