@startwbs 夕食を作るWBS
title 夕食を作るWBS

+ 夕食を作る

** 買い物をする
+++ 集金する
*** スーパーで買い物

** 料理をする
+++ お米を炊く
*** メインを作る
*** 副菜を作る
*** スープを作る
*** デザートを作る

** 食べる準備をする
+++ テーブルを拭く
*** ランチョンマットを準備する
*** カトラリーを準備する

** 食べる

@endwbs