@startwbs メインを作る
title ハンバーグを作る

+ ハンバーグを作る

** タネを作る
+++ 玉ねぎをみじん切りにする
*** 玉ねぎを炒める
*** 合挽き肉と玉ねぎを合わせてこねる
*** パン粉、牛乳、調味料を入れてこねる

** 火を通す
+++ 三等分し楕円形に成形する
*** フライパンで焼く
*** ハンバーグソースを作る

** 盛り付ける
+++ お皿を出す
*** ハンバーグをのせる
*** ソースをかける

@endwbs