@startwbs デザートを作る
title プリンを作る

+ プリンを作る
** カラメルを作る
+++ 鍋にグラニュー糖・水を入れて煮詰める
*** 火を止めて湯を加えて混ぜる
*** プリン容器3つに入れる
** プリン液を作る
+++ ボウルに卵を割り入れてグラニュー糖を加えて混ぜる
*** 鍋に牛乳を入れて沸騰する前に火を止める
*** 卵液に牛乳を少しずつ入れて混ぜる
*** プリン容器に卵液を入れる
*** 鍋に布巾をかぶせプリン容器を並べる
*** プリン容器の半分くらいの高さになるように水を入れる
*** 蓋をして中火で熱し湯気が出てきたらごく弱火で20～30分蒸す
** プリン液を蒸して冷やす
+++ 粗熱が取れたら冷蔵庫に入れて冷やす
** 盛り付ける
+++ お皿を準備する
*** プリン容器の底をお湯で温めてカラメルを溶かす
*** 皿の上にプリン容器を上下ひっくり返してのせてプリンを取り出す
@endwbs